"""add_timestamps_to_teams

Revision ID: 6fd8d018e09b
Revises: 0dd924962a86
Create Date: 2026-06-13 02:13:04.028225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd8d018e09b'
down_revision: Union[str, Sequence[str], None] = '0dd924962a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    # ### end Alembic commands ###
